/* 영어 어드벤처 학습 내용
 * {EN} = 영어 이름, {KO} = 한글 이름. {KO야}·{KO이야}·{KO이에요}는 받침에 맞춰 바뀌어요. (예: 지수야 / 민준아)
 */
const P=(en,ko,e)=>({en,ko,e});
const WARMUP=[P("Hello!","안녕!","👋"),P("Thank you.","고마워요.","🙏")];
const WARMUP_ADULT=[P("Nice to meet you.","만나서 반가워요.","🤝"),P("How's your day going?","오늘 하루 어때요?","☀️")];
const W_BEGINNER=[
{id:'home',icon:'🏠',name:'우리 집',desc:'아침부터 잠들기 전까지',bg:'#e0f2fe',
 phrases:[P("Good morning!","좋은 아침!","☀️"),P("I'm sleepy.","졸려요.","😪"),P("I'm ready.","준비됐어요.","🙌"),P("Where is my bag?","내 가방 어디 있어요?","🎒"),P("I can't find it.","못 찾겠어요.","🔍"),P("I'm home!","다녀왔습니다!","🏡"),P("I'm going to bed.","이제 자러 갈게요.","🛏️"),P("Good night!","잘 자요!","🌙")],
 patterns:[{en:"Where is my ___?",ko:"내 ___ 어디 있어요?",slots:[P("bag","가방","🎒"),P("book","책","📕"),P("hat","모자","🧢"),P("toothbrush","칫솔","🪥")]},
  {en:"I'm ___.",ko:"나 ___.",slots:[P("sleepy","졸려","😪"),P("hungry","배고파","🤤"),P("ready","준비됐어","🙌"),P("cold","추워","🥶")]}],
 dialogs:[[['you',"Good morning, {EN}!","좋은 아침, {KO야}!"],['me',"Good morning! I'm sleepy.","좋은 아침! 졸려요."],['you',"Time to get up! It's school time!","일어나야지! 학교 갈 시간이야!"],['me',"Okay... Where is my bag?","알았어요… 내 가방 어디 있어요?"],['you',"It's on the chair.","의자 위에 있어."],['me',"Thanks! I'm ready!","고마워요! 준비됐어요!"]],
  [['you',"It's late. Are you sleepy?","늦었네. 졸리니?"],['me',"Yes, I'm sleepy.","네, 졸려요."],['you',"It's time for bed.","잘 시간이야."],['me',"Okay. I'm going to bed.","네. 자러 갈게요."],['you',"Good night, {EN}!","잘 자, {KO야}!"],['me',"Good night!","안녕히 주무세요!"]]],
 missions:[`아침에 엄마·아빠에게 "Good morning!" 인사하기`,`학교 갈 준비가 끝나면 "I'm ready!" 외치기`,`잘 때 "Good night!" 말하고 자기`]},

{id:'table',icon:'🍽️',name:'식탁',desc:'먹고 마시고 부탁하기',bg:'#ffedd5',
 phrases:[P("I'm hungry.","배고파요.","🤤"),P("I want some water.","물 먹고 싶어요.","💧"),P("Pass me the salt, please.","소금 좀 건네주세요.","🧂"),P("It's delicious!","맛있어요!","😋"),P("Can I have more?","더 먹어도 돼요?","🍚"),P("I'm full.","배불러요.","😌"),P("I don't like carrots.","당근은 싫어요.","🥕"),P("Thank you for the meal.","잘 먹었습니다.","🙏")],
 patterns:[{en:"I want some ___.",ko:"___ 먹고 싶어요.",slots:[P("water","물","💧"),P("milk","우유","🥛"),P("juice","주스","🧃"),P("bread","빵","🍞")]},
  {en:"Pass me the ___, please.",ko:"___ 좀 건네주세요.",slots:[P("salt","소금","🧂"),P("spoon","숟가락","🥄"),P("water","물","💧"),P("cup","컵","🥤")]}],
 dialogs:[[['you',"Are you hungry?","배고프니?"],['me',"Yes, I'm hungry!","네, 배고파요!"],['you',"Here's your dinner.","저녁 여기 있어."],['me',"Thank you! It's delicious!","고마워요! 맛있어요!"],['you',"Do you want more?","더 줄까?"],['me',"No, thank you. I'm full.","아니요, 괜찮아요. 배불러요."]],
  [['you',"What do you want to drink?","뭐 마실래?"],['me',"I want some water.","물 마시고 싶어요."],['you',"Here you go. Do you want some carrots?","여기 있어. 당근도 줄까?"],['me',"No, thanks. I don't like carrots.","아니요. 당근은 싫어요."],['you',"Just one bite!","한 입만 먹어봐!"],['me',"Okay... It's delicious!","알았어요… 맛있네요!"]]],
 missions:[`식탁에서 "Pass me the water, please." 말하기`,`밥을 먹고 "It's delicious!" 말하기`,`배고플 때 "I'm hungry." 라고 말하기`]},

{id:'outside',icon:'🛒',name:'외출 & 쇼핑',desc:'가게에서 필요한 말',bg:'#fce7f3',
 phrases:[P("I want this.","이거 갖고 싶어요.","👉"),P("How much is it?","얼마예요?","💰"),P("Can I have this?","이거 사도 돼요?","🎁"),P("I like this one.","이게 좋아요.","💖"),P("Which one?","어떤 거?","🤔"),P("This one, please.","이걸로 주세요.","☝️"),P("It's too big.","너무 커요.","🐘"),P("Let's go!","가자!","🚶‍♀️")],
 patterns:[{en:"Can I have a ___?",ko:"___ 가져도 돼요?",slots:[P("candy","사탕","🍬"),P("balloon","풍선","🎈"),P("sticker","스티커","⭐"),P("cookie","쿠키","🍪")]},
  {en:"It's too ___.",ko:"너무 ___.",slots:[P("big","커요","🐘"),P("small","작아요","🐭"),P("expensive","비싸요","💸"),P("long","길어요","📏")]}],
 dialogs:[[['you',"Can I help you?","도와드릴까요?"],['me',"I want this.","이거 갖고 싶어요."],['you',"Which one?","어떤 거요?"],['me',"This one, please. How much is it?","이걸로 주세요. 얼마예요?"],['you',"It's two dollars.","2달러예요."],['me',"Thank you!","고맙습니다!"]],
  [['me',"Mom, I like this one!","엄마, 이게 좋아요!"],['you',"Hmm, it's too big.","음, 너무 크다."],['me',"How about this one?","이건 어때요?"],['you',"Good!","좋아!"],['me',"Can I have this?","이거 사도 돼요?"],['you',"Sure! Let's go!","그래! 가자!"]]],
 missions:[`마트에서 사고 싶은 걸 가리키며 "I want this!" 말하기`,`물건 가격이 궁금할 때 "How much is it?" 물어보기`]},

{id:'play',icon:'🎮',name:'놀이 & 친구',desc:'같이 놀고 이야기하기',bg:'#ede9fe',
 phrases:[P("Let's play!","같이 놀자!","🤸"),P("Do you want to play?","같이 놀래?","🙋‍♀️"),P("Your turn.","네 차례야.","👉"),P("My turn!","내 차례!","✋"),P("That's fun!","재밌다!","😆"),P("I win!","내가 이겼다!","🏆"),P("Good job!","잘했어!","👍"),P("One more time!","한 번 더!","🔁")],
 patterns:[{en:"Let's play ___!",ko:"___ 하자!",slots:[P("tag","술래잡기","🏃"),P("cards","카드놀이","🃏"),P("soccer","축구","⚽"),P("hide-and-seek","숨바꼭질","🙈")]},
  {en:"Do you want to ___?",ko:"___?",slots:[P("play","같이 놀래","🤸"),P("draw","그림 그릴래","🎨"),P("dance","춤출래","💃"),P("sing","노래할래","🎤")]}],
 dialogs:[[['me',"Do you want to play?","같이 놀래?"],['you',"Sure! Let's play cards!","좋아! 카드놀이 하자!"],['me',"My turn first!","내가 먼저 할게!"],['you',"Okay!","그래!"],['me',"Your turn.","이제 네 차례야."],['you',"I win!","내가 이겼다!"],['me',"That's fun! One more time!","재밌다! 한 번 더!"]],
  [['you',"Your turn, {EN}.","네 차례야, {KO야}."],['me',"Yes! I win!","앗싸! 내가 이겼다!"],['you',"Good job!","잘했어!"],['me',"That's fun!","재밌다!"],['you',"One more time?","한 번 더 할까?"],['me',"Okay! Let's play!","좋아! 같이 놀자!"]]],
 missions:[`가족과 보드게임 하면서 "My turn!" "Your turn." 말하기`,`놀이가 끝나면 "That's fun!" 말하기`]},

{id:'travel',icon:'✈️',name:'여행',desc:'호텔·카페·길에서 말하기',bg:'#d1fae5',
 phrases:[P("Excuse me.","실례합니다.","🙋"),P("Where is the bathroom?","화장실 어디예요?","🚻"),P("I need help.","도와주세요.","🆘"),P("Can I have some water?","물 좀 주시겠어요?","💧"),P("I'm lost.","길을 잃었어요.","🗺️"),P("Nice to meet you!","만나서 반가워요!","🤝"),P("I'm from Korea.","저는 한국에서 왔어요.","🇰🇷"),P("Thank you so much!","정말 고마워요!","💐")],
 patterns:[{en:"Where is the ___?",ko:"___ 어디예요?",slots:[P("bathroom","화장실","🚻"),P("elevator","엘리베이터","🛗"),P("exit","출구","🚪"),P("pool","수영장","🏊")]},
  {en:"Can I have some ___?",ko:"___ 좀 주시겠어요?",slots:[P("water","물","💧"),P("ice","얼음","🧊"),P("juice","주스","🧃"),P("napkins","냅킨","🧻")]}],
 dialogs:[[['me',"Excuse me.","실례합니다."],['you',"Yes? Do you need help?","네? 도움이 필요하니?"],['me',"Where is the bathroom?","화장실 어디예요?"],['you',"It's over there.","저쪽에 있어요."],['me',"Thank you so much!","정말 고마워요!"],['you',"You're welcome!","천만에요!"]],
  [['you',"Hello! Nice to meet you!","안녕! 만나서 반가워요!"],['me',"Nice to meet you, too!","저도 만나서 반가워요!"],['you',"Where are you from?","어디서 왔어요?"],['me',"I'm from Korea.","저는 한국에서 왔어요."],['you',"Welcome!","환영해요!"],['me',"Thank you so much!","정말 고마워요!"]]],
 missions:[`가족에게 질문할 때 "Excuse me." 하고 시작하기`,`집에서 "Where is the bathroom?" 물어보기 놀이`]},

{id:'school',icon:'🏫',name:'학교',desc:'친구와 선생님에게 말하기',bg:'#fef9c3',
 phrases:[P("What's your name?","이름이 뭐야?","📛"),P("My name is {EN}.","내 이름은 {KO이야}.","🦄"),P("Can you help me?","도와줄 수 있어요?","🙏"),P("I don't understand.","이해가 안 돼요.","🤔"),P("Can I borrow a pencil?","연필 빌려도 돼?","✏️"),P("Can I go to the bathroom?","화장실 가도 돼요?","🚻"),P("I'm done!","다 했어요!","✅"),P("See you tomorrow!","내일 봐!","👋")],
 patterns:[{en:"Can I borrow a ___?",ko:"___ 빌려도 돼?",slots:[P("pencil","연필","✏️"),P("ruler","자","📏"),P("crayon","크레파스","🖍️"),P("book","책","📕")]},
  {en:"Can I go to the ___?",ko:"___ 가도 돼요?",slots:[P("bathroom","화장실","🚻"),P("nurse's office","보건실","🏥"),P("library","도서관","📚"),P("playground","놀이터","🛝")]}],
 dialogs:[[['you',"Hi! What's your name?","안녕! 이름이 뭐야?"],['me',"My name is {EN}. What's your name?","내 이름은 {KO이야}. 너는?"],['you',"I'm Mina. Nice to meet you!","나는 미나야. 만나서 반가워!"],['me',"Nice to meet you, too!","나도 만나서 반가워!"],['you',"Let's be friends!","우리 친구 하자!"],['me',"Okay!","좋아!"]],
  [['you',"What's wrong, {EN}?","왜 그래, {KO야}?"],['me',"I can't find my pencil.","연필을 못 찾겠어."],['you',"Oh no!","어떡해!"],['me',"Can I borrow a pencil?","연필 빌려도 돼?"],['you',"Sure! Here you go.","그럼! 여기 있어."],['me',"Thank you!","고마워!"]]],
 missions:[`가족 앞에서 "My name is {EN}." 로 자기소개하기`,`가족에게 "Can I borrow a pencil?" 말하고 연필 빌리기`]},

{id:'chat',icon:'💬',name:'일상 대화',desc:'내 기분과 하루를 말하기',bg:'#fae8ff',
 phrases:[P("How are you?","기분 어때?","🙂"),P("I'm good, thank you.","좋아, 고마워.","😄"),P("I'm happy.","기분 좋아요.","😊"),P("I'm tired.","피곤해요.","😩"),P("I like it.","좋아요.","👍"),P("I don't like it.","싫어요.","👎"),P("Me too!","나도!","🙌"),P("I had fun today!","오늘 재밌었어요!","🎉")],
 patterns:[{en:"I'm ___.",ko:"나 ___.",slots:[P("happy","기분 좋아","😊"),P("tired","피곤해","😩"),P("sad","슬퍼","😢"),P("excited","신나","🤩")]},
  {en:"I like ___.",ko:"나는 ___ 좋아.",slots:[P("cats","고양이","🐱"),P("pizza","피자","🍕"),P("music","음악","🎵"),P("unicorns","유니콘","🦄")]}],
 dialogs:[[['you',"How are you, {EN}?","기분 어때, {KO야}?"],['me',"I'm happy!","기분 좋아요!"],['you',"Why?","왜?"],['me',"I had fun today!","오늘 재밌었어요!"],['you',"That's great!","멋지다!"],['me',"How are you?","엄마는 기분 어때요?"],['you',"I'm good, thank you.","좋아, 고마워."]],
  [['you',"You look tired.","피곤해 보이네."],['me',"Yes, I'm tired.","네, 피곤해요."],['you',"Do you want some milk?","우유 줄까?"],['me',"Yes, please.","네, 주세요."],['you',"Here you go.","여기 있어."],['me',"Thank you! I like it.","고마워요! 좋아요."]]],
 missions:[`잠들기 전 "I had fun today!" 또는 "I'm tired." 로 오늘 기분 말하기`,`가족에게 "How are you?" 물어보기`]},

{id:'free',icon:'🌟',name:'자유 대화',desc:'배운 영어를 섞어서 말하기',bg:'#e0e7ff',
 phrases:[P("What are you doing?","뭐 하고 있어?","👀"),P("I'm reading a book.","책 읽고 있어.","📖"),P("What do you want?","뭐 원해?","🎁"),P("What do you like?","뭐 좋아해?","💭"),P("Tell me about your day.","오늘 하루 얘기해 줘.","🗓️"),P("I went to school.","학교에 갔어.","🏫"),P("I played with my friends.","친구들이랑 놀았어.","👭"),P("That's great!","멋지다!","🌈")],
 patterns:[{en:"I'm ___.",ko:"___이야.",slots:[P("reading a book","책 읽는 중","📖"),P("drawing","그림 그리는 중","🎨"),P("eating","밥 먹는 중","🍽️"),P("watching TV","TV 보는 중","📺")]},
  {en:"I played with my ___.",ko:"___ 놀았어.",slots:[P("friends","친구들이랑","👭"),P("dog","강아지랑","🐶"),P("mom","엄마랑","👩"),P("dad","아빠랑","👨")]}],
 dialogs:[[['you',"What are you doing?","뭐 하고 있어?"],['me',"I'm reading a book.","책 읽고 있어요."],['you',"Do you like it?","재밌어?"],['me',"Yes, I like it!","네, 재밌어요!"],['you',"Tell me about your day.","오늘 하루 얘기해 줘."],['me',"I went to school. I played with my friends.","학교에 갔어요. 친구들이랑 놀았어요."],['you',"That's great!","멋지다!"]],
  [['you',"What do you want for dinner?","저녁 뭐 먹고 싶어?"],['me',"I want pizza!","피자 먹고 싶어요!"],['you',"Pizza again?","또 피자?"],['me',"Yes! I like pizza!","네! 피자 좋아요!"],['you',"Okay, let's have pizza!","그래, 피자 먹자!"],['me',"Yay! Thank you!","야호! 고마워요!"]]],
 missions:[`저녁에 가족에게 오늘 한 일을 영어 한 문장으로 말하기`,`가족이 "What are you doing?" 물으면 영어로 대답하기`]}
];
const W_INTERMEDIATE=[
{id:'home',icon:'🏠',name:'우리 집',desc:'하루 일과를 길게 말하기',bg:'#e0f2fe',
 phrases:[P("Can you wake me up at seven?","7시에 깨워 줄 수 있어요?","⏰"),P("I brushed my teeth already.","벌써 이 닦았어요.","🪥"),P("What's for breakfast?","아침 뭐예요?","🍳"),P("Can I watch TV after homework?","숙제하고 TV 봐도 돼요?","📺"),P("I'll clean up my room.","제 방 치울게요.","🧹"),P("Where did you put my socks?","제 양말 어디 뒀어요?","🧦"),P("I'm going to take a shower.","샤워하러 갈게요.","🚿"),P("Can you read me a story?","이야기 읽어 줄 수 있어요?","📖")],
 patterns:[{en:"Can I ___ after homework?",ko:"숙제하고 ___도 돼요?",slots:[P("watch TV","TV 봐","📺"),P("play games","게임해","🎮"),P("go outside","밖에 나가","🌳"),P("eat a snack","간식 먹어","🍪")]},
  {en:"Where did you put my ___?",ko:"내 ___ 어디 뒀어요?",slots:[P("socks","양말","🧦"),P("shoes","신발","👟"),P("jacket","점퍼","🧥"),P("homework","숙제","📒")]}],
 dialogs:[[['you',"{EN}, it's time to wake up!","{KO야}, 일어날 시간이야!"],['me',"Five more minutes, please.","5분만 더요."],['you',"No, you'll be late for school.","안 돼, 학교 늦겠다."],['me',"Okay. What's for breakfast?","알았어요. 아침 뭐예요?"],['you',"Eggs and toast.","계란이랑 토스트야."],['me',"Yummy! I'll be ready soon.","맛있겠다! 금방 준비할게요."]],
  [['you',"Did you finish your homework?","숙제 다 했니?"],['me',"Yes! Can I watch TV now?","네! 이제 TV 봐도 돼요?"],['you',"First, clean up your room.","먼저 방 치우렴."],['me',"Okay, I'll clean up my room.","네, 방 치울게요."],['you',"Good job! Now you can watch TV.","잘했어! 이제 TV 봐도 돼."],['me',"Thank you! You're the best!","고마워요! 최고예요!"]]],
 missions:[`아침에 "What's for breakfast?" 물어보기`,`잠들기 전에 "Can you read me a story?" 부탁하기`]},

{id:'table',icon:'🍽️',name:'식탁',desc:'더 자세히 부탁하고 말하기',bg:'#ffedd5',
 phrases:[P("Can I have some more rice?","밥 좀 더 먹어도 돼요?","🍚"),P("This soup is too hot.","이 국 너무 뜨거워요.","🥣"),P("Could you pass me the water?","물 좀 건네주실래요?","💧"),P("I'd like some orange juice.","오렌지 주스 마시고 싶어요.","🧃"),P("I don't want any onions.","양파는 빼 주세요.","🧅"),P("What are we having for dinner?","저녁 뭐 먹어요?","🍽️"),P("This is my favorite food!","이거 제일 좋아하는 음식이에요!","😍"),P("May I be excused?","먼저 일어나도 될까요?","🙇")],
 patterns:[{en:"Can I have some more ___?",ko:"___ 좀 더 먹어도 돼요?",slots:[P("rice","밥","🍚"),P("soup","국","🥣"),P("chicken","치킨","🍗"),P("fruit","과일","🍎")]},
  {en:"This soup is too ___.",ko:"이 국 너무 ___.",slots:[P("hot","뜨거워요","🔥"),P("salty","짜요","🧂"),P("spicy","매워요","🌶️"),P("cold","차가워요","🧊")]}],
 dialogs:[[['me',"What are we having for dinner?","저녁 뭐 먹어요?"],['you',"We're having chicken soup.","치킨 수프 먹을 거야."],['me',"Yay! This is my favorite food!","야호! 제일 좋아하는 음식이에요!"],['you',"Be careful. It's hot.","조심해. 뜨거워."],['me',"Oops! This soup is too hot.","앗! 이 국 너무 뜨거워요."],['you',"Blow on it first.","먼저 후후 불어 먹어."]],
  [['you',"Do you want some more?","더 먹을래?"],['me',"Yes, can I have some more rice?","네, 밥 좀 더 먹어도 돼요?"],['you',"Sure. Anything else?","그럼. 다른 건?"],['me',"Could you pass me the water?","물 좀 건네주실래요?"],['you',"Here you go.","여기 있어."],['me',"Thank you. Everything is delicious!","고맙습니다. 다 맛있어요!"]]],
 missions:[`밥 먹을 때 "Can I have some more rice?" 말하기`,`저녁 전에 "What are we having for dinner?" 물어보기`]},

{id:'outside',icon:'🛒',name:'외출 & 쇼핑',desc:'가게에서 묻고 고르기',bg:'#fce7f3',
 phrases:[P("How much does this cost?","이거 얼마예요?","💰"),P("Do you have a smaller one?","더 작은 거 있어요?","🔎"),P("Can I try it on?","입어 봐도 돼요?","👗"),P("I'm just looking.","그냥 구경하는 거예요.","👀"),P("It's on sale!","세일 중이에요!","🏷️"),P("I'll take this one.","이걸로 할게요.","☝️"),P("Where can I find the toys?","장난감은 어디 있어요?","🧸"),P("Can I pay with this card?","이 카드로 계산해도 돼요?","💳")],
 patterns:[{en:"Do you have a ___ one?",ko:"___ 거 있어요?",slots:[P("smaller","더 작은","🐭"),P("bigger","더 큰","🐘"),P("cheaper","더 싼","💵"),P("pink","분홍색","🩷")]},
  {en:"Where can I find the ___?",ko:"___ 어디 있어요?",slots:[P("toys","장난감은","🧸"),P("books","책은","📚"),P("snacks","과자는","🍪"),P("shoes","신발은","👟")]}],
 dialogs:[[['you',"Hello! Can I help you?","안녕하세요! 도와드릴까요?"],['me',"I'm just looking. Thank you.","그냥 구경하는 거예요. 고맙습니다."],['you',"Okay. These shirts are on sale.","네. 이 셔츠들 세일 중이에요."],['me',"Can I try it on?","입어 봐도 돼요?"],['you',"Of course! How is it?","물론이죠! 어때요?"],['me',"It's too big. Do you have a smaller one?","너무 커요. 더 작은 거 있어요?"]],
  [['me',"Excuse me. Where can I find the toys?","실례합니다. 장난감은 어디 있어요?"],['you',"They're on the second floor.","2층에 있어요."],['me',"How much does this cost?","이거 얼마예요?"],['you',"It's ten dollars.","10달러예요."],['me',"I'll take this one. Can I pay with this card?","이걸로 할게요. 이 카드로 계산해도 돼요?"],['you',"Sure! Here's your receipt.","그럼요! 영수증 여기 있어요."]]],
 missions:[`가게 놀이하면서 "How much does this cost?" 물어보기`,`옷을 입어 볼 때 "Can I try it on?" 말하기`]},

{id:'play',icon:'🎮',name:'놀이 & 친구',desc:'친구와 사이좋게 말하기',bg:'#ede9fe',
 phrases:[P("Can I play with you?","같이 놀아도 돼?","🙋"),P("Let's take turns.","돌아가면서 하자.","🔄"),P("It's not fair!","불공평해!","😤"),P("Who's going first?","누가 먼저 할래?","☝️"),P("You're really good at this!","너 이거 진짜 잘한다!","🌟"),P("I'm almost done.","거의 다 했어.","⏳"),P("Let's play again tomorrow.","내일 또 놀자.","📅"),P("Don't worry, it's okay.","걱정 마, 괜찮아.","🤗")],
 patterns:[{en:"You're really good at ___!",ko:"너 ___ 진짜 잘한다!",slots:[P("soccer","축구","⚽"),P("drawing","그림","🎨"),P("singing","노래","🎤"),P("puzzles","퍼즐","🧩")]},
  {en:"Let's ___ together.",ko:"같이 ___.",slots:[P("build a castle","성 쌓자","🏰"),P("draw a picture","그림 그리자","🎨"),P("ride bikes","자전거 타자","🚲"),P("do a puzzle","퍼즐 하자","🧩")]}],
 dialogs:[[['me',"Hi! Can I play with you?","안녕! 같이 놀아도 돼?"],['you',"Sure! Who's going first?","좋아! 누가 먼저 할래?"],['me',"You can go first.","너 먼저 해."],['you',"Thanks! Wow, I won!","고마워! 와, 내가 이겼다!"],['me',"You're really good at this!","너 이거 진짜 잘한다!"],['you',"Let's play again tomorrow.","내일 또 놀자."]],
  [['you',"It's not fair! You always go first.","불공평해! 너만 맨날 먼저 하잖아."],['me',"Sorry. Let's take turns.","미안. 돌아가면서 하자."],['you',"Okay. My turn now.","좋아. 이제 내 차례야."],['me',"Go ahead!","해 봐!"],['you',"Oops, I made a mistake.","앗, 실수했다."],['me',"Don't worry, it's okay.","걱정 마, 괜찮아."]]],
 missions:[`놀이할 때 "Let's take turns." 말하기`,`가족을 칭찬하며 "You're really good at this!" 말하기`]},

{id:'travel',icon:'✈️',name:'여행',desc:'차·비행기·여행지에서 말하기',bg:'#d1fae5',
 phrases:[P("We're going on a trip!","우리 여행 가요!","🧳"),P("How long does it take?","얼마나 걸려요?","⏱️"),P("Can I have a window seat?","창가 자리 앉아도 돼요?","🪟"),P("I need to go to the bathroom.","화장실 가야 해요.","🚻"),P("Are we there yet?","아직 멀었어요?","🚗"),P("Can you take a picture of us?","저희 사진 찍어 주실래요?","📸"),P("This place is amazing!","여기 정말 멋져요!","🤩"),P("I want to swim in the pool.","수영장에서 수영하고 싶어요.","🏊")],
 patterns:[{en:"I want to ___.",ko:"___고 싶어요.",slots:[P("swim in the pool","수영장에서 수영하","🏊"),P("go to the beach","바닷가에 가","🏖️"),P("eat ice cream","아이스크림 먹","🍦"),P("see the animals","동물 보","🦒")]},
  {en:"Can I have a ___ seat?",ko:"___ 자리 앉아도 돼요?",slots:[P("window","창가","🪟"),P("front","앞","⬆️"),P("back","뒤","⬇️"),P("aisle","통로","🚶")]}],
 dialogs:[[['me',"Are we there yet?","아직 멀었어요?"],['you',"Not yet. Be patient.","아직이야. 조금만 참아."],['me',"How long does it take?","얼마나 걸려요?"],['you',"About one more hour.","한 시간쯤 더."],['me',"I need to go to the bathroom.","화장실 가야 해요."],['you',"Okay, let's stop at the next rest area.","알았어, 다음 휴게소에서 쉬자."]],
  [['me',"Wow! This place is amazing!","와! 여기 정말 멋져요!"],['you',"Let's take a picture.","사진 찍자."],['me',"Excuse me. Can you take a picture of us?","실례합니다. 저희 사진 찍어 주실래요?"],['you',"Sure! Say cheese!","그럼요! 치즈!"],['me',"Thank you so much!","정말 고맙습니다!"],['you',"You're welcome. Have a nice trip!","천만에요. 즐거운 여행 되세요!"]]],
 missions:[`차를 탈 때 "How long does it take?" 물어보기`,`사진 찍을 때 "Can you take a picture of us?" 말하기`]},

{id:'school',icon:'🏫',name:'학교',desc:'수업과 쉬는 시간에 말하기',bg:'#fef9c3',
 phrases:[P("Good morning, teacher!","선생님, 안녕하세요!","🍎"),P("I forgot my homework.","숙제를 깜빡했어요.","😥"),P("Can you say that again?","다시 말해 주실래요?","🔁"),P("How do you spell it?","철자가 어떻게 돼요?","🔤"),P("May I sit here?","여기 앉아도 돼?","🪑"),P("What's your favorite subject?","제일 좋아하는 과목이 뭐야?","📚"),P("My favorite subject is art.","제일 좋아하는 과목은 미술이야.","🎨"),P("Let's have lunch together.","같이 점심 먹자.","🍱")],
 patterns:[{en:"My favorite subject is ___.",ko:"제일 좋아하는 과목은 ___.",slots:[P("art","미술이야","🎨"),P("math","수학이야","➗"),P("music","음악이야","🎵"),P("science","과학이야","🔬")]},
  {en:"I forgot my ___.",ko:"___ 깜빡했어요.",slots:[P("homework","숙제를","📒"),P("pencil case","필통을","✏️"),P("water bottle","물병을","🥤"),P("lunch box","도시락을","🍱")]}],
 dialogs:[[['you',"Good morning, class!","여러분, 안녕!"],['me',"Good morning, teacher!","선생님, 안녕하세요!"],['you',"Did you bring your homework?","숙제 가져왔니?"],['me',"Oh no, I forgot my homework.","어떡해요, 숙제를 깜빡했어요."],['you',"That's okay. Bring it tomorrow.","괜찮아. 내일 가져오렴."],['me',"Thank you. I will.","고맙습니다. 그럴게요."]],
  [['me',"Hi! May I sit here?","안녕! 여기 앉아도 돼?"],['you',"Sure! What's your favorite subject?","그럼! 제일 좋아하는 과목이 뭐야?"],['me',"My favorite subject is art. How about you?","나는 미술이 제일 좋아. 너는?"],['you',"I like music.","난 음악이 좋아."],['me',"Cool! Let's have lunch together.","멋지다! 같이 점심 먹자."],['you',"Okay!","좋아!"]]],
 missions:[`가족에게 "What's your favorite subject?" 물어보기`,`못 알아들었을 때 "Can you say that again?" 말하기`]},

{id:'chat',icon:'💬',name:'일상 대화',desc:'이유와 기분을 함께 말하기',bg:'#fae8ff',
 phrases:[P("How was your day?","오늘 하루 어땠어?","🌤️"),P("It was a great day!","정말 좋은 하루였어요!","🌈"),P("I'm a little nervous.","조금 떨려요.","😬"),P("I'm so excited!","너무 신나요!","🤩"),P("Why are you sad?","왜 슬퍼?","😢"),P("Because I lost my toy.","장난감을 잃어버려서요.","🧸"),P("That makes me happy.","그래서 기분이 좋아요.","😊"),P("I feel much better now.","이제 훨씬 나아졌어요.","💪")],
 patterns:[{en:"I'm a little ___.",ko:"조금 ___.",slots:[P("nervous","떨려요","😬"),P("tired","피곤해요","😩"),P("hungry","배고파요","🤤"),P("sleepy","졸려요","😪")]},
  {en:"I feel ___ now.",ko:"이제 ___.",slots:[P("better","나아졌어요","💪"),P("happy","기분 좋아요","😊"),P("calm","마음이 편해요","😌"),P("strong","힘이 나요","🦸")]}],
 dialogs:[[['you',"How was your day?","오늘 하루 어땠어?"],['me',"It was a great day!","정말 좋은 하루였어요!"],['you',"What happened?","무슨 일 있었어?"],['me',"I got a sticker from my teacher.","선생님한테 스티커 받았어요."],['you',"Wow, I'm proud of you!","와, 자랑스럽다!"],['me',"Thanks! That makes me happy.","고마워요! 그래서 기분 좋아요."]],
  [['you',"Why are you sad?","왜 슬퍼?"],['me',"Because I lost my toy.","장난감을 잃어버려서요."],['you',"Let's look for it together.","같이 찾아보자."],['me',"Look! Here it is!","보세요! 여기 있어요!"],['you',"Do you feel better?","기분 좀 나아졌니?"],['me',"Yes, I feel much better now.","네, 이제 훨씬 나아졌어요."]]],
 missions:[`저녁에 가족에게 "How was your day?" 물어보기`,`오늘 기분을 "I'm a little ___." 로 말해 보기`]},

{id:'free',icon:'🌟',name:'자유 대화',desc:'꿈과 계획을 말하기',bg:'#e0e7ff',
 phrases:[P("What did you do today?","오늘 뭐 했어?","🗓️"),P("I went to the park with my friends.","친구들이랑 공원에 갔어요.","🌳"),P("What do you want to be?","커서 뭐가 되고 싶어?","🌟"),P("I want to be a doctor.","의사가 되고 싶어요.","🩺"),P("What's your favorite animal?","제일 좋아하는 동물이 뭐야?","🐾"),P("I like dogs because they're cute.","강아지가 귀여워서 좋아요.","🐶"),P("What are you going to do this weekend?","이번 주말에 뭐 할 거야?","📅"),P("I'm going to visit my grandma.","할머니 댁에 갈 거예요.","👵")],
 patterns:[{en:"I want to be a ___.",ko:"___ 되고 싶어요.",slots:[P("doctor","의사가","🩺"),P("teacher","선생님이","👩‍🏫"),P("singer","가수가","🎤"),P("scientist","과학자가","🔬")]},
  {en:"I'm going to ___ this weekend.",ko:"이번 주말에 ___.",slots:[P("visit my grandma","할머니 댁에 갈 거예요","👵"),P("go camping","캠핑 갈 거예요","⛺"),P("watch a movie","영화 볼 거예요","🎬"),P("bake cookies","쿠키 구울 거예요","🍪")]}],
 dialogs:[[['you',"What did you do today?","오늘 뭐 했어?"],['me',"I went to the park with my friends.","친구들이랑 공원에 갔어요."],['you',"What did you play?","뭐 하고 놀았어?"],['me',"We played tag. It was so fun!","술래잡기했어요. 진짜 재밌었어요!"],['you',"What are you going to do this weekend?","이번 주말엔 뭐 할 거야?"],['me',"I'm going to visit my grandma.","할머니 댁에 갈 거예요."]],
  [['you',"What do you want to be?","커서 뭐가 되고 싶어?"],['me',"I want to be a doctor.","의사가 되고 싶어요."],['you',"Why?","왜?"],['me',"Because I want to help sick people.","아픈 사람들을 돕고 싶어서요."],['you',"That's a wonderful dream!","멋진 꿈이구나!"],['me',"Thank you! What did you want to be?","고마워요! 어릴 때 뭐가 되고 싶었어요?"]]],
 missions:[`"What do you want to be?" 질문에 영어로 대답하기`,`주말 계획을 "I'm going to ___." 로 말해 보기`]}
];
const W_ADVANCED=[
{id:'neighbor',icon:'🏘️',name:'이웃 & 동네',desc:'이웃과 인사하고 부탁하기',bg:'#e0f2fe',
 phrases:[P("Hi, I just moved in next door.","안녕하세요, 옆집에 막 이사 왔어요.","📦"),P("Nice to finally meet you.","드디어 뵙네요.","🤝"),P("Do you know a good place to eat around here?","이 근처에 괜찮은 식당 아세요?","🍝"),P("Sorry about the noise last night.","어젯밤 시끄러워서 죄송했어요.","🙏"),P("Could you keep an eye on my place while I'm away?","제가 없는 동안 집 좀 봐 주실 수 있을까요?","🏠"),P("I think this package is yours.","이 택배 그쪽 거 같아요.","📬"),P("Let me know if you need anything.","필요한 거 있으면 말씀하세요.","💬"),P("Have a good one!","좋은 하루 보내세요!","👋")],
 patterns:[{en:"Do you know a good ___ around here?",ko:"이 근처에 괜찮은 ___ 아세요?",slots:[P("bakery","빵집","🥐"),P("dentist","치과","🦷"),P("hair salon","미용실","💇"),P("park","공원","🌳")]},
  {en:"Could you ___ while I'm away?",ko:"제가 없는 동안 ___?",slots:[P("water my plants","화분에 물 좀 주실 수 있을까요","🪴"),P("feed my cat","고양이 밥 좀 주실 수 있을까요","🐈"),P("pick up my mail","우편물 좀 챙겨 주실 수 있을까요","📬"),P("keep an eye on my place","집 좀 봐 주실 수 있을까요","🏠")]}],
 dialogs:[[['me',"Hi, I just moved in next door.","안녕하세요, 옆집에 막 이사 왔어요."],['you',"Oh, welcome to the neighborhood! I'm Sarah.","아, 이사 오신 걸 환영해요! 저는 사라예요."],['me',"I'm {EN}. Nice to finally meet you.","저는 {KO이에요}. 드디어 뵙네요."],['you',"Do you need help with anything?","도와드릴 거 있으세요?"],['me',"Actually, do you know a good place to eat around here?","사실, 이 근처에 괜찮은 식당 아세요?"],['you',"There's a great Italian place on the corner.","모퉁이에 정말 괜찮은 이탈리안 식당이 있어요."],['me',"Thanks! Let me know if you need anything.","고마워요! 필요한 거 있으면 말씀하세요."]],
  [['you',"Hi! I think this package is yours.","안녕하세요! 이 택배 그쪽 거 같아요."],['me',"Oh, thank you so much! Sorry for the trouble.","아, 정말 감사해요! 번거롭게 해 드려서 죄송해요."],['you',"No problem at all.","전혀요."],['me',"By the way, I'm going away next week. Could you keep an eye on my place?","그런데 다음 주에 집을 비우는데요. 집 좀 봐 주실 수 있을까요?"],['you',"Sure, no problem.","그럼요, 문제없어요."],['me',"You're the best. Have a good one!","정말 최고예요. 좋은 하루 보내세요!"]]],
 missions:[`오늘 배운 문장 하나를 가족에게 영어로 써먹어 보기`,`배운 표현 하나를 아이에게 가르쳐 주기`]},

{id:'restaurant',icon:'🍷',name:'카페 & 레스토랑',desc:'주문하고 요청하기',bg:'#ffedd5',
 phrases:[P("Can I get a table for three?","3명 자리 있나요?","🍽️"),P("Could we see the menu, please?","메뉴판 좀 볼 수 있을까요?","📋"),P("What do you recommend?","뭘 추천하세요?","👨‍🍳"),P("I'll have the same, please.","저도 같은 걸로 할게요.","✌️"),P("Could I get this without onions?","이거 양파 빼고 주실 수 있나요?","🧅"),P("Excuse me, this isn't what I ordered.","저기요, 이건 제가 주문한 게 아니에요.","🙋"),P("Can we get the check, please?","계산서 좀 주시겠어요?","🧾"),P("Could I get this to go?","이거 포장해 주실 수 있나요?","🥡")],
 patterns:[{en:"Could I get this without ___?",ko:"이거 ___ 빼고 주실 수 있나요?",slots:[P("onions","양파","🧅"),P("ice","얼음","🧊"),P("cheese","치즈","🧀"),P("cilantro","고수","🌿")]},
  {en:"Can I get ___, please?",ko:"___ 주시겠어요?",slots:[P("a small latte","라테 작은 사이즈로","☕"),P("a glass of water","물 한 잔","💧"),P("a refill","리필","🔁"),P("a box for this","포장 용기","📦")]}],
 dialogs:[[['you',"Hi, how many?","안녕하세요, 몇 분이세요?"],['me',"Can I get a table for three?","3명 자리 있나요?"],['you',"Sure, right this way. Here's the menu.","네, 이쪽으로 오세요. 메뉴판 여기 있습니다."],['me',"Thanks. What do you recommend?","감사해요. 뭘 추천하세요?"],['you',"Our pasta is really popular.","저희 파스타가 인기가 많아요."],['me',"Great. Could I get it without onions?","좋아요. 양파 빼고 주실 수 있나요?"],['you',"Of course.","물론이죠."]],
  [['me',"Excuse me, this isn't what I ordered.","저기요, 이건 제가 주문한 게 아니에요."],['you',"Oh, I'm so sorry. What did you order?","아, 정말 죄송합니다. 뭘 주문하셨죠?"],['me',"I ordered the chicken salad.","치킨 샐러드 주문했어요."],['you',"I'll bring it right away.","바로 가져다 드릴게요."],['me',"Thanks. And can we get the check, please?","감사해요. 그리고 계산서 좀 주시겠어요?"],['you',"Sure. Would you like anything to go?","네. 포장하실 건 있으세요?"],['me',"Yes, could I get this to go?","네, 이거 포장해 주실 수 있나요?"]]],
 missions:[`카페에서 주문할 문장을 영어로 먼저 혼잣말해 보기`,`저녁 식탁에서 "Could you pass me ___?" 를 가족에게 써 보기`]},

{id:'shopping',icon:'🛍️',name:'쇼핑 & 교환·환불',desc:'고르고 바꾸고 환불하기',bg:'#fce7f3',
 phrases:[P("I'm looking for a gift for my child.","아이 선물을 찾고 있어요.","🎁"),P("Do you have this in a different size?","이거 다른 사이즈 있나요?","📏"),P("Is this on sale?","이거 세일하나요?","🏷️"),P("I'd like to return this.","이거 반품하고 싶어요.","↩️"),P("Can I exchange it for a larger size?","더 큰 사이즈로 교환할 수 있나요?","🔄"),P("I have the receipt right here.","영수증 여기 있어요.","🧾"),P("It doesn't fit me.","저한테 안 맞아요.","👖"),P("Can I get a refund?","환불 받을 수 있나요?","💵")],
 patterns:[{en:"Do you have this in ___?",ko:"이거 ___ 있나요?",slots:[P("a different size","다른 사이즈","📏"),P("black","검은색","⚫"),P("a medium","미디엄 사이즈","👕"),P("a smaller size","더 작은 사이즈","🔽")]},
  {en:"I'm looking for a gift for my ___.",ko:"___ 선물을 찾고 있어요.",slots:[P("daughter","딸","👧"),P("son","아들","👦"),P("husband","남편","👨"),P("mother","엄마","👩")]}],
 dialogs:[[['you',"Hi, can I help you find something?","안녕하세요, 찾으시는 거 있으세요?"],['me',"Yes, I'm looking for a gift for my child.","네, 아이 선물을 찾고 있어요."],['you',"How old are they?","아이가 몇 살이에요?"],['me',"They're in elementary school. They love unicorns.","초등학생이에요. 유니콘을 정말 좋아해요."],['you',"How about this unicorn backpack?","이 유니콘 가방은 어떠세요?"],['me',"Perfect! Is this on sale?","딱이네요! 이거 세일하나요?"],['you',"Yes, it's twenty percent off.","네, 20% 할인이에요."]],
  [['me',"Hi, I'd like to return this.","안녕하세요, 이거 반품하고 싶어요."],['you',"Is there a problem with it?","무슨 문제가 있나요?"],['me',"It doesn't fit me. Can I exchange it for a larger size?","저한테 안 맞아서요. 더 큰 사이즈로 교환할 수 있나요?"],['you',"Sure. Do you have the receipt?","그럼요. 영수증 있으세요?"],['me',"I have the receipt right here.","영수증 여기 있어요."],['you',"Great. Here's a large.","좋아요. 라지 사이즈 여기 있습니다."],['me',"Thank you for your help.","도와주셔서 감사해요."]]],
 missions:[`온라인 쇼핑할 때 상품 설명을 영어로 소리 내어 읽어 보기`,`"Do you have this in ___?" 로 사고 싶은 물건 3가지 말해 보기`]},

{id:'parent',icon:'🏫',name:'학교 & 학부모',desc:'학교에 연락하고 상담하기',bg:'#fef9c3',
 phrases:[P("Hi, I'm calling about my child.","안녕하세요, 저희 아이 일로 연락드렸어요.","📞"),P("My child has a fever and can't come to school today.","아이가 열이 나서 오늘 학교에 못 가요.","🤒"),P("How is my child doing in class?","아이가 수업 시간에 어떻게 지내나요?","📚"),P("Is there anything I can do at home?","집에서 제가 해 줄 수 있는 게 있을까요?","🏡"),P("Could you send me the schedule?","일정 좀 보내 주실 수 있나요?","🗓️"),P("I'll pick my child up early today.","오늘은 아이를 일찍 데리러 갈게요.","🚗"),P("Thank you for everything you do.","늘 애써 주셔서 감사해요.","💐"),P("What time does school get out?","학교는 몇 시에 끝나요?","⏰")],
 patterns:[{en:"Could you send me the ___?",ko:"___ 좀 보내 주실 수 있나요?",slots:[P("schedule","일정","🗓️"),P("lunch menu","급식 메뉴","🍱"),P("homework list","숙제 목록","📒"),P("field trip form","현장학습 신청서","🚌")]},
  {en:"My child has ___ and can't come to school today.",ko:"아이가 ___ 오늘 학교에 못 가요.",slots:[P("a fever","열이 나서","🤒"),P("a cold","감기에 걸려서","🤧"),P("a stomachache","배가 아파서","🤢"),P("a dentist appointment","치과 예약이 있어서","🦷")]}],
 dialogs:[[['you',"Hello, this is the school office.","안녕하세요, 학교 행정실입니다."],['me',"Hi, I'm calling about my child.","안녕하세요, 저희 아이 일로 연락드렸어요."],['you',"Sure. How can I help?","네. 무엇을 도와드릴까요?"],['me',"My child has a fever and can't come to school today.","아이가 열이 나서 오늘 학교에 못 가요."],['you',"Oh, I'm sorry to hear that. I'll let the teacher know.","저런, 안타깝네요. 선생님께 전달할게요."],['me',"Thank you. Could you send me today's homework?","감사합니다. 오늘 숙제 좀 보내 주실 수 있나요?"],['you',"Of course. I hope your child feels better soon.","물론이죠. 아이가 빨리 낫길 바랄게요."]],
  [['me',"Thank you for meeting with me.","만나 주셔서 감사해요."],['you',"My pleasure. Your child is doing great.","별말씀을요. 아이가 아주 잘하고 있어요."],['me',"That's good to hear. How is my child doing in reading?","다행이네요. 읽기는 어떻게 하고 있나요?"],['you',"Very well, but writing needs some practice.","아주 잘해요. 다만 쓰기는 연습이 좀 필요해요."],['me',"Is there anything I can do at home?","집에서 제가 해 줄 수 있는 게 있을까요?"],['you',"Reading together every night would really help.","매일 밤 같이 책을 읽으면 정말 도움이 될 거예요."],['me',"Great. Thank you for everything you do.","좋아요. 늘 애써 주셔서 감사해요."]]],
 missions:[`아이와 영어 그림책 한 권을 같이 소리 내어 읽기`,`선생님께 보낼 짧은 영어 메시지를 상상해서 말해 보기`]},

{id:'hotel',icon:'✈️',name:'여행 · 호텔 · 공항',desc:'체크인부터 길 찾기까지',bg:'#d1fae5',
 phrases:[P("I'd like to check in, please.","체크인하려고요.","🛎️"),P("I have a reservation under {EN}.","{KO} 이름으로 예약했어요.","📋"),P("Is breakfast included?","조식 포함인가요?","🥐"),P("Could I get a late checkout?","체크아웃 좀 늦게 할 수 있을까요?","🕐"),P("The air conditioner in my room isn't working.","방 에어컨이 작동을 안 해요.","❄️"),P("Where is the gate for this flight?","이 비행기 탑승구가 어디예요?","🛫"),P("My luggage didn't come out.","제 짐이 안 나왔어요.","🧳"),P("How do I get to downtown from here?","여기서 시내까지 어떻게 가요?","🚕")],
 patterns:[{en:"The ___ in my room isn't working.",ko:"방 ___ 작동을 안 해요.",slots:[P("air conditioner","에어컨이","❄️"),P("TV","TV가","📺"),P("shower","샤워기가","🚿"),P("Wi-Fi","와이파이가","📶")]},
  {en:"How do I get to ___ from here?",ko:"여기서 ___ 어떻게 가요?",slots:[P("downtown","시내까지","🏙️"),P("the airport","공항까지","✈️"),P("the beach","해변까지","🏖️"),P("the subway station","지하철역까지","🚇")]}],
 dialogs:[[['me',"Hi, I'd like to check in, please.","안녕하세요, 체크인하려고요."],['you',"Sure. May I have your name?","네. 성함이 어떻게 되시죠?"],['me',"I have a reservation under {EN}.","{KO} 이름으로 예약했어요."],['you',"Got it. Here's your key. You're in room 702.","확인됐습니다. 키 여기 있어요. 702호입니다."],['me',"Thank you. Is breakfast included?","감사해요. 조식 포함인가요?"],['you',"Yes, from seven to ten on the second floor.","네, 2층에서 7시부터 10시까지예요."]],
  [['me',"Hi, the air conditioner in my room isn't working.","안녕하세요, 방 에어컨이 작동을 안 해요."],['you',"I'm sorry about that. I'll send someone up right away.","죄송합니다. 바로 사람을 올려 보낼게요."],['me',"Thank you. Also, could I get a late checkout?","감사해요. 그리고 체크아웃 좀 늦게 할 수 있을까요?"],['you',"Sure, we can do noon.","네, 12시까지 가능해요."],['me',"Perfect. And how do I get to downtown from here?","좋아요. 그리고 여기서 시내까지 어떻게 가요?"],['you',"The bus stop is right in front of the hotel.","버스 정류장이 호텔 바로 앞에 있어요."]]],
 missions:[`다음 여행에서 쓸 문장 3개를 골라 소리 내어 연습하기`,`가족 여행 계획을 영어 두 문장으로 말해 보기`]},

{id:'hospital',icon:'🏥',name:'병원 & 약국',desc:'증상 말하고 약 묻기',bg:'#fee2e2',
 phrases:[P("I'd like to make an appointment.","진료 예약하고 싶어요.","📅"),P("I've had a headache since yesterday.","어제부터 머리가 아파요.","🤕"),P("My child has a high fever.","아이가 열이 많이 나요.","🌡️"),P("Do I need a prescription for this?","이거 처방전이 필요한가요?","📝"),P("How often should I take this?","이거 얼마나 자주 먹어야 하나요?","💊"),P("Are there any side effects?","부작용이 있나요?","⚠️"),P("I'm allergic to penicillin.","저는 페니실린 알레르기가 있어요.","🚫"),P("Does my insurance cover this?","보험 적용되나요?","💳")],
 patterns:[{en:"I've had ___ since yesterday.",ko:"어제부터 ___.",slots:[P("a headache","머리가 아파요","🤕"),P("a sore throat","목이 아파요","😷"),P("a stomachache","배가 아파요","🤢"),P("a runny nose","콧물이 나요","🤧")]},
  {en:"I'm allergic to ___.",ko:"저는 ___ 알레르기가 있어요.",slots:[P("penicillin","페니실린","💊"),P("peanuts","땅콩","🥜"),P("shrimp","새우","🦐"),P("cats","고양이","🐈")]}],
 dialogs:[[['you',"What brings you in today?","오늘 어디가 불편해서 오셨어요?"],['me',"I've had a headache since yesterday.","어제부터 머리가 아파요."],['you',"Do you have a fever too?","열도 있으세요?"],['me',"A little. And I'm allergic to penicillin.","조금요. 그리고 페니실린 알레르기가 있어요."],['you',"Thanks for letting me know. I'll prescribe something else.","알려 주셔서 감사해요. 다른 약으로 처방할게요."],['me',"Thank you. Are there any side effects?","감사합니다. 부작용이 있나요?"],['you',"You might feel a little sleepy.","조금 졸릴 수 있어요."]],
  [['me',"Hi, do I need a prescription for this?","안녕하세요, 이거 처방전이 필요한가요?"],['you',"No, you can buy it over the counter.","아니요, 처방전 없이 사실 수 있어요."],['me',"Great. How often should I take this?","좋아요. 이거 얼마나 자주 먹어야 하나요?"],['you',"Twice a day, after meals.","하루 두 번, 식후에요."],['me',"Got it. Does my insurance cover this?","알겠어요. 보험 적용되나요?"],['you',"Let me check for you.","확인해 드릴게요."]]],
 missions:[`오늘 몸 상태를 영어 한 문장으로 말해 보기`,`집에 있는 약 하나의 영어 설명을 소리 내어 읽어 보기`]},

{id:'smalltalk',icon:'☕',name:'스몰토크',desc:'가볍게 안부 나누기',bg:'#fae8ff',
 phrases:[P("How's it going?","잘 지내요?","🙂"),P("Long time no see!","오랜만이에요!","🤗"),P("What have you been up to?","요즘 어떻게 지냈어요?","💬"),P("Not much, just busy with work.","별일 없어요, 그냥 일 때문에 바빠요.","💼"),P("How was your weekend?","주말 어떻게 보냈어요?","🌤️"),P("The weather is beautiful today, isn't it?","오늘 날씨 정말 좋죠?","☀️"),P("I've been meaning to ask you something.","물어보고 싶은 게 있었어요.","🤔"),P("Let's grab coffee sometime.","언제 커피 한잔해요.","☕")],
 patterns:[{en:"Let's grab ___ sometime.",ko:"언제 ___ 해요.",slots:[P("coffee","커피 한잔","☕"),P("lunch","점심 같이","🥪"),P("dinner","저녁 같이","🍝"),P("a drink","한잔","🍷")]},
  {en:"How was your ___?",ko:"___ 어땠어요?",slots:[P("weekend","주말","🌤️"),P("trip","여행","✈️"),P("vacation","휴가","🏖️"),P("day","오늘 하루","📅")]}],
 dialogs:[[['you',"{EN}! Long time no see!","{KO} 씨! 오랜만이에요!"],['me',"Hey! How's it going?","안녕하세요! 잘 지내요?"],['you',"Pretty good. What have you been up to?","잘 지내요. 요즘 어떻게 지냈어요?"],['me',"Not much, just busy with my kids.","별일 없어요, 그냥 애들 때문에 바빠요."],['you',"I know the feeling!","무슨 말인지 알아요!"],['me',"Let's grab coffee sometime.","언제 커피 한잔해요."],['you',"I'd love that!","좋아요!"]],
  [['me',"How was your weekend?","주말 어떻게 보냈어요?"],['you',"It was great. We went hiking.","좋았어요. 등산 갔어요."],['me',"Nice! The weather was beautiful, wasn't it?","좋네요! 날씨 정말 좋았죠?"],['you',"It really was. How about you?","정말 그랬어요. 그쪽은요?"],['me',"I just relaxed at home with my family.","그냥 가족이랑 집에서 쉬었어요."],['you',"Sounds perfect.","완벽하네요."]]],
 missions:[`가족에게 영어로 "How was your day?" 묻고 대답 듣기`,`오늘 날씨를 영어 한 문장으로 말해 보기`]},

{id:'repair',icon:'🛠️',name:'집 문제 & 수리',desc:'관리실·수리 기사와 이야기하기',bg:'#e0e7ff',
 phrases:[P("The sink is leaking.","싱크대에서 물이 새요.","🚰"),P("Could you send someone to fix it?","고칠 사람 좀 보내 주실 수 있나요?","🔧"),P("When would be a good time?","언제가 좋으세요?","🕒"),P("I'll be home all afternoon.","오후 내내 집에 있을 거예요.","🏠"),P("How much will it cost?","비용이 얼마나 들까요?","💰"),P("It's been like this for a week.","일주일째 이래요.","📆"),P("Could you call me before you come?","오시기 전에 전화 주실 수 있나요?","📱"),P("Thanks for coming so quickly.","빨리 와 주셔서 감사해요.","🙏")],
 patterns:[{en:"The ___ is leaking.",ko:"___에서 물이 새요.",slots:[P("sink","싱크대","🚰"),P("toilet","변기","🚽"),P("roof","지붕","🏠"),P("washing machine","세탁기","🧺")]},
  {en:"I'll be home ___.",ko:"___ 집에 있을 거예요.",slots:[P("all afternoon","오후 내내","🌇"),P("after three","3시 이후에","🕒"),P("tomorrow morning","내일 아침에","🌅"),P("all day on Saturday","토요일 하루 종일","📅")]}],
 dialogs:[[['you',"Building management. How can I help you?","관리실입니다. 무엇을 도와드릴까요?"],['me',"Hi, the sink in my kitchen is leaking.","안녕하세요, 주방 싱크대에서 물이 새요."],['you',"How long has it been like that?","언제부터 그랬어요?"],['me',"It's been like this for a week.","일주일째 이래요."],['you',"I see. When would be a good time to come by?","그렇군요. 언제 방문하면 좋을까요?"],['me',"I'll be home all afternoon. Could you call me before you come?","오후 내내 집에 있을 거예요. 오시기 전에 전화 주실 수 있나요?"],['you',"Sure, I'll call you.","네, 전화드릴게요."]],
  [['you',"Hi, I'm here to fix the sink.","안녕하세요, 싱크대 고치러 왔어요."],['me',"Thanks for coming so quickly. It's right here.","빨리 와 주셔서 감사해요. 바로 여기예요."],['you',"I see the problem. I need to replace this part.","문제를 찾았어요. 이 부품을 바꿔야 해요."],['me',"How much will it cost?","비용이 얼마나 들까요?"],['you',"About fifty dollars, including labor.","인건비 포함해서 50달러쯤이에요."],['me',"Okay, please go ahead.","알겠어요, 진행해 주세요."]]],
 missions:[`집에서 고장 난 물건 하나를 영어로 설명해 보기`,`이번 주 일정을 "I'll be home ___." 로 말해 보기`]}
];
const W_MASTER=[
{id:'catchup',icon:'🗣️',name:'근황 토크',desc:'오랜만에 만난 사람과 자연스럽게',bg:'#e0f2fe',
 phrases:[P("It's been ages! How have you been?","진짜 오랜만이다! 어떻게 지냈어?","🤗"),P("I can't complain.","그럭저럭 잘 지내.","😌"),P("Things have been pretty hectic lately.","요즘 정신없이 바빴어.","🌀"),P("We should catch up over dinner.","저녁 먹으면서 밀린 얘기 하자.","🍝"),P("I'll have to take a rain check.","다음 기회로 미뤄야겠어.","☔"),P("Speaking of which, how's your new job?","말 나온 김에, 새 직장은 어때?","💼"),P("I've been meaning to call you.","안 그래도 전화하려고 했어.","📱"),P("Let's keep in touch.","계속 연락하고 지내자.","💌")],
 patterns:[{en:"Things have been pretty ___ lately.",ko:"요즘 꽤 ___.",slots:[P("hectic","정신없었어","🌀"),P("slow","한가했어","🐢"),P("stressful","스트레스였어","😩"),P("exciting","신났어","🎉")]},
  {en:"We should catch up over ___.",ko:"___ 밀린 얘기 하자.",slots:[P("dinner","저녁 먹으면서","🍝"),P("coffee","커피 마시면서","☕"),P("lunch","점심 먹으면서","🥗"),P("a drink","한잔하면서","🍷")]}],
 dialogs:[[['you',"{EN}? Wow, it's been ages! How have you been?","{KO}? 와, 진짜 오랜만이다! 어떻게 지냈어?"],['me',"I can't complain. How about you?","그럭저럭 잘 지내. 너는?"],['you',"Things have been pretty hectic lately. I just started a new job.","요즘 정신없이 바빴어. 새 직장에 막 들어갔거든."],['me',"Oh, congrats! Speaking of which, how's it going?","와, 축하해! 말 나온 김에, 어때?"],['you',"So far, so good. It's a bit of a learning curve, though.","아직까진 좋아. 배울 게 좀 많긴 하지만."],['me',"We should catch up over dinner sometime.","언제 저녁 먹으면서 밀린 얘기 하자."]],
  [['you',"Are you free this Friday? A few of us are getting together.","이번 금요일에 시간 돼? 몇 명 모이기로 했어."],['me',"Ah, I'd love to, but I'll have to take a rain check.","아, 정말 가고 싶은데 다음 기회로 미뤄야겠어."],['you',"No worries. Did something come up?","괜찮아. 무슨 일 있어?"],['me',"My kid has a school event that night.","그날 밤에 아이 학교 행사가 있어서."],['you',"Totally understand. Next time, then!","완전 이해해. 그럼 다음에!"],['me',"Definitely. Let's keep in touch!","꼭. 계속 연락하자!"]]],
 missions:[`오늘 있었던 일을 영어로 30초 동안 혼잣말해 보기`,`배운 표현 하나를 실제 대화나 메시지에 써 보기`]},

{id:'phone',icon:'📞',name:'전화 & 예약',desc:'전화로 일정 잡고 바꾸기',bg:'#ffedd5',
 phrases:[P("I'm calling to reschedule my appointment.","예약 일정을 변경하려고 전화드렸어요.","📅"),P("Would sometime next week work?","다음 주 중에 가능할까요?","🗓️"),P("Could you put me on the waiting list?","대기자 명단에 올려 주실 수 있나요?","📝"),P("Sorry, could you speak a little slower?","죄송한데, 조금만 천천히 말씀해 주실래요?","🐢"),P("Let me double-check my schedule.","제 일정 한번 다시 확인해 볼게요.","🔍"),P("I'd like to cancel my reservation.","예약을 취소하고 싶어요.","❌"),P("Could you text me the confirmation?","확인 내용을 문자로 보내 주실 수 있나요?","💬"),P("I'll hold, thank you.","기다릴게요, 감사합니다.","⏳")],
 patterns:[{en:"Would ___ work?",ko:"___ 괜찮을까요?",slots:[P("sometime next week","다음 주 중에","🗓️"),P("Tuesday afternoon","화요일 오후","🕑"),P("early morning","이른 아침","🌅"),P("the same time tomorrow","내일 같은 시간","⏰")]},
  {en:"I'm calling to ___ my appointment.",ko:"예약을 ___ 전화드렸어요.",slots:[P("reschedule","변경하려고","📅"),P("confirm","확인하려고","✅"),P("cancel","취소하려고","❌"),P("move up","앞당기려고","⏩")]}],
 dialogs:[[['you',"Good morning, Bright Dental. How may I help you?","안녕하세요, 브라이트 치과입니다. 무엇을 도와드릴까요?"],['me',"Hi, I'm calling to reschedule my appointment.","안녕하세요, 예약 일정을 변경하려고 전화드렸어요."],['you',"Sure. What's your name, please?","네. 성함이 어떻게 되세요?"],['me',"It's {EN}. My appointment is on Thursday at two.","{KO}입니다. 목요일 2시 예약이에요."],['you',"Got it. Would next Monday at ten work?","확인했습니다. 다음 주 월요일 10시 괜찮으세요?"],['me',"Let me double-check my schedule. Yes, that works.","제 일정 다시 확인해 볼게요. 네, 괜찮아요."],['you',"Great. You're all set.","좋습니다. 예약 완료되었어요."],['me',"Could you text me the confirmation?","확인 내용을 문자로 보내 주실 수 있나요?"]],
  [['you',"I'm afraid we're fully booked tonight.","죄송하지만 오늘 밤은 예약이 다 찼어요."],['me',"Oh, that's too bad. Could you put me on the waiting list?","아, 아쉽네요. 대기자 명단에 올려 주실 수 있나요?"],['you',"Sure. Can I get a number to reach you?","네. 연락받으실 번호 알려 주시겠어요?"],['me',"Sorry, could you speak a little slower?","죄송한데, 조금만 천천히 말씀해 주실래요?"],['you',"Of course. What's your phone number?","물론이죠. 전화번호가 어떻게 되세요?"],['me',"It's 555-0123. Thanks so much.","555-0123이에요. 정말 감사해요."]]],
 missions:[`실제 예약 전화를 한다고 상상하고 첫 문장을 소리 내어 말해 보기`,`못 알아들었을 때 쓸 표현 2가지를 외워서 말해 보기`]},

{id:'complain',icon:'🙇',name:'정중하게 불만 말하기',desc:'기분 상하지 않게 요구하기',bg:'#fce7f3',
 phrases:[P("I hate to bring this up, but...","이런 말 하기 좀 그렇지만...","😅"),P("I was wondering if you could help me with something.","혹시 좀 도와주실 수 있을까 해서요.","🤲"),P("I think there might be a mistake on my bill.","계산서에 착오가 있는 것 같아요.","🧾"),P("I'd appreciate it if you could look into it.","확인해 주시면 감사하겠어요.","🔍"),P("That's not quite what I expected.","제가 기대한 것과는 좀 달라요.","🤔"),P("I understand, but this is the third time.","이해는 하지만, 이번이 세 번째예요.","3️⃣"),P("Is there anything you can do about it?","어떻게 좀 해 주실 수 있을까요?","🙏"),P("I really appreciate your help.","도와주셔서 정말 감사해요.","💐")],
 patterns:[{en:"I think there might be a mistake on my ___.",ko:"제 ___에 착오가 있는 것 같아요.",slots:[P("bill","계산서","🧾"),P("order","주문","📦"),P("receipt","영수증","🗒️"),P("reservation","예약","📅")]},
  {en:"I'd appreciate it if you could ___.",ko:"___ 주시면 감사하겠어요.",slots:[P("look into it","확인해","🔍"),P("call me back","다시 전화해","📞"),P("fix it today","오늘 고쳐","🔧"),P("give me a refund","환불해","💵")]}],
 dialogs:[[['me',"Excuse me, I think there might be a mistake on my bill.","저기요, 계산서에 착오가 있는 것 같아요."],['you',"Oh, let me take a look.","아, 한번 볼게요."],['me',"We were charged for two desserts, but we only had one.","디저트 두 개가 계산됐는데 하나만 먹었어요."],['you',"You're right. I'm so sorry about that.","맞네요. 정말 죄송합니다."],['me',"No problem. These things happen.","괜찮아요. 그럴 수도 있죠."],['you',"I'll fix that right away.","바로 수정해 드릴게요."],['me',"I really appreciate your help.","도와주셔서 정말 감사해요."]],
  [['me',"Hi, I hate to bring this up, but my internet went out again.","안녕하세요, 이런 말 하기 좀 그렇지만, 인터넷이 또 끊겼어요."],['you',"I'm sorry to hear that. We can send a technician next week.","불편을 드려 죄송합니다. 다음 주에 기사님을 보내 드릴 수 있어요."],['me',"I understand, but this is the third time this month.","이해는 하지만, 이번 달에만 세 번째예요."],['you',"I completely understand your frustration.","답답하신 마음 충분히 이해합니다."],['me',"Is there anything you can do about it sooner?","좀 더 빨리 어떻게 해 주실 수 있을까요?"],['you',"Let me see. I can get someone there tomorrow morning.","확인해 볼게요. 내일 오전에 보내 드릴 수 있어요."],['me',"That would be great. Thank you.","그러면 좋겠어요. 감사합니다."]]],
 missions:[`불편했던 일 하나를 정중한 영어 문장으로 바꿔 말해 보기`,`"I'd appreciate it if you could ___." 로 가족에게 부탁해 보기`]},

{id:'teacher',icon:'🎒',name:'학부모 상담',desc:'선생님과 깊이 있게 이야기하기',bg:'#fef9c3',
 phrases:[P("I'd like to talk about how my child is adjusting.","아이가 어떻게 적응하고 있는지 이야기 나누고 싶어요.","🌱"),P("My child seems a little shy at school.","아이가 학교에서 좀 수줍어하는 것 같아요.","🙈"),P("English isn't our first language at home.","저희 집은 영어가 모국어가 아니에요.","🗣️"),P("What would you suggest?","어떻게 하면 좋을까요?","💡"),P("Could we set up a meeting sometime this week?","이번 주 중에 면담 시간을 잡을 수 있을까요?","📅"),P("I really appreciate you keeping me in the loop.","계속 소식 알려 주셔서 정말 감사해요.","🔄"),P("Please let me know if anything comes up.","무슨 일 있으면 꼭 알려 주세요.","📩"),P("We'll work on it together at home.","집에서도 같이 노력해 볼게요.","🤝")],
 patterns:[{en:"My child seems a little ___ at school.",ko:"아이가 학교에서 좀 ___ 것 같아요.",slots:[P("shy","수줍어하는","🙈"),P("tired","피곤해하는","😴"),P("stressed","스트레스받는","😣"),P("bored","지루해하는","🥱")]},
  {en:"Could we set up a meeting ___?",ko:"___ 면담 시간을 잡을 수 있을까요?",slots:[P("sometime this week","이번 주 중에","📅"),P("after school","방과 후에","🏫"),P("on Friday","금요일에","🗓️"),P("next month","다음 달에","📆")]}],
 dialogs:[[['you',"Thanks for coming in today.","오늘 와 주셔서 감사해요."],['me',"Thank you for making the time. I'd like to talk about how my child is adjusting.","시간 내 주셔서 감사해요. 아이가 어떻게 적응하고 있는지 이야기 나누고 싶어요."],['you',"Overall, things are going well. Your child is very kind to others.","전반적으로 잘 지내고 있어요. 친구들에게 아주 다정해요."],['me',"That's great to hear. But my child seems a little shy at school.","다행이네요. 그런데 학교에서 좀 수줍어하는 것 같아서요."],['you',"A bit, yes. English isn't easy at first.","조금요. 처음엔 영어가 쉽지 않죠."],['me',"English isn't our first language at home. What would you suggest?","저희 집은 영어가 모국어가 아니에요. 어떻게 하면 좋을까요?"],['you',"Reading picture books together would really help.","그림책을 같이 읽으면 정말 도움이 될 거예요."]],
  [['you',"I wanted to let you know your child had a small fall at recess.","쉬는 시간에 아이가 살짝 넘어졌다는 걸 알려 드리려고요."],['me',"Oh no. Is my child okay?","어머. 아이는 괜찮나요?"],['you',"Just a little scrape. The nurse took care of it.","살짝 긁힌 정도예요. 보건 선생님이 처치해 주셨어요."],['me',"Thank you. I really appreciate you keeping me in the loop.","감사해요. 계속 소식 알려 주셔서 정말 감사해요."],['you',"Of course. I'll keep an eye on things.","물론이죠. 계속 지켜볼게요."],['me',"Please let me know if anything comes up.","무슨 일 있으면 꼭 알려 주세요."]]],
 missions:[`아이의 장점 3가지를 영어로 말해 보기`,`선생님께 쓸 감사 인사를 영어로 말해 보기`]},

{id:'opinion',icon:'💭',name:'의견 말하기',desc:'동의·반대·보류를 부드럽게',bg:'#d1fae5',
 phrases:[P("In my opinion, it's worth a try.","제 생각엔 해 볼 만한 것 같아요.","👍"),P("I see your point, but...","무슨 말인지는 알겠는데요...","🤔"),P("I couldn't agree more.","전적으로 동의해요.","💯"),P("That's a good point.","좋은 지적이에요.","☝️"),P("I'm on the fence about it.","아직 결정을 못 했어요.","⚖️"),P("It depends on the situation.","상황에 따라 달라요.","🔀"),P("To be honest, I'm not so sure.","솔직히 잘 모르겠어요.","😶"),P("Let's look at it from a different angle.","다른 각도에서 한번 봐요.","🔭")],
 patterns:[{en:"In my opinion, it's ___.",ko:"제 생각엔 ___.",slots:[P("worth a try","해 볼 만한 것 같아요","👍"),P("too risky","너무 위험한 것 같아요","⚠️"),P("a great idea","좋은 생각인 것 같아요","💡"),P("not worth it","그럴 가치가 없는 것 같아요","👎")]},
  {en:"I'm on the fence about ___.",ko:"___ 아직 결정을 못 했어요.",slots:[P("it","그거","⚖️"),P("moving","이사하는 거","🏠"),P("the new school","새 학교","🏫"),P("getting a dog","강아지 키우는 거","🐶")]}],
 dialogs:[[['you',"Do you think we should get a dog?","우리 강아지 키워야 할까?"],['me',"Hmm, I'm on the fence about it.","음, 아직 결정을 못 했어."],['you',"Why? The kids would love it.","왜? 애들이 정말 좋아할 텐데."],['me',"I see your point, but it's a big responsibility.","무슨 말인지는 알겠는데, 책임이 크잖아."],['you',"That's a good point. Maybe we could foster one first.","좋은 지적이야. 먼저 임시 보호부터 해 볼까?"],['me',"In my opinion, that's worth a try.","내 생각엔 그건 해 볼 만한 것 같아."]],
  [['you',"Social media is just bad for kids.","SNS는 그냥 애들한테 나빠."],['me',"To be honest, I'm not so sure.","솔직히 잘 모르겠어."],['you',"Really? Why not?","정말? 왜?"],['me',"It depends on the situation. Some content is educational.","상황에 따라 달라. 교육적인 콘텐츠도 있거든."],['you',"Hmm, I hadn't thought about it that way.","음, 그렇게는 생각 못 해 봤네."],['me',"Let's look at it from a different angle.","다른 각도에서 한번 보자."]]],
 missions:[`오늘 뉴스 하나에 대한 내 의견을 영어 두 문장으로 말해 보기`,`가족과 작은 주제로 영어로 찬반 말해 보기`]},

{id:'favor',icon:'🤲',name:'부탁 & 거절',desc:'부담 없이 부탁하고 거절하기',bg:'#fee2e2',
 phrases:[P("Would you mind if I opened the window?","창문 좀 열어도 괜찮을까요?","🪟"),P("I was hoping you could do me a favor.","부탁 하나 드려도 될까 해서요.","🙏"),P("I'd love to, but I'm swamped this week.","그러고 싶은데 이번 주는 너무 바빠요.","📚"),P("I'm afraid I can't make it.","아쉽지만 못 갈 것 같아요.","😔"),P("No pressure at all.","전혀 부담 갖지 마세요.","🕊️"),P("Let me get back to you on that.","그건 생각해 보고 다시 말씀드릴게요.","⏳"),P("That's very kind of you to offer.","제안해 주셔서 정말 고마워요.","💝"),P("Thanks for understanding.","이해해 주셔서 고마워요.","🤝")],
 patterns:[{en:"Would you mind if I ___?",ko:"제가 ___도 괜찮을까요?",slots:[P("opened the window","창문 좀 열어","🪟"),P("sat here","여기 앉아","🪑"),P("left a little early","조금 일찍 가","🚪"),P("called you later","나중에 전화해","📞")]},
  {en:"I'd love to, but I'm ___ this week.",ko:"그러고 싶은데 이번 주는 ___.",slots:[P("swamped","너무 바빠요","📚"),P("out of town","다른 지역에 가 있어요","🧳"),P("a bit under the weather","몸이 좀 안 좋아요","🤒"),P("booked solid","일정이 꽉 찼어요","📅")]}],
 dialogs:[[['you',"Hey, I was hoping you could do me a favor.","있잖아, 부탁 하나 해도 될까 해서."],['me',"Sure, what is it?","그럼, 뭔데?"],['you',"Could you help me move this Saturday?","이번 토요일에 이사하는 것 좀 도와줄 수 있어?"],['me',"I'd love to, but I'm swamped this week.","그러고 싶은데 이번 주는 너무 바빠."],['you',"No pressure at all. I totally get it.","전혀 부담 갖지 마. 완전 이해해."],['me',"Thanks for understanding. Let me know if I can help another time.","이해해 줘서 고마워. 다음에 도울 일 있으면 말해."]],
  [['you',"I can drive you to the airport tomorrow if you want.","원하면 내일 공항까지 태워 줄게."],['me',"That's very kind of you to offer.","제안해 줘서 정말 고마워."],['you',"It's no trouble at all.","전혀 번거롭지 않아."],['me',"Let me get back to you on that. I might take a taxi.","생각해 보고 다시 말해 줄게. 택시 탈 수도 있어서."],['you',"Sure, just text me.","그래, 문자만 줘."],['me',"Will do. Thanks again!","그럴게. 다시 한번 고마워!"]]],
 missions:[`정중하게 거절하는 문장 하나를 외워서 말해 보기`,`가족에게 "Would you mind if I ___?" 로 부탁해 보기`]},

{id:'empathy',icon:'💗',name:'감정 & 공감',desc:'위로하고 축하하기',bg:'#fae8ff',
 phrases:[P("I'm so sorry to hear that.","그 말 들으니 정말 안타까워요.","😢"),P("That must have been really hard.","정말 힘드셨겠어요.","🫂"),P("I'm here if you need anything.","필요한 거 있으면 언제든 말해요.","🤝"),P("I know exactly how you feel.","그 마음 정말 잘 알아요.","💗"),P("I'm so happy for you!","정말 잘됐어요, 내 일처럼 기뻐요!","🎉"),P("You must be so proud.","정말 뿌듯하시겠어요.","🏅"),P("Hang in there.","조금만 힘내요.","💪"),P("Take all the time you need.","천천히 하셔도 돼요.","⏳")],
 patterns:[{en:"That must have been really ___.",ko:"정말 ___겠어요.",slots:[P("hard","힘드셨","🫂"),P("stressful","스트레스받으셨","😣"),P("exciting","신나셨","🤩"),P("scary","무서우셨","😱")]},
  {en:"I'm so ___ for you!",ko:"정말 ___!",slots:[P("happy","잘됐어요","🎉"),P("proud","자랑스러워요","🏅"),P("excited","기대돼요","🤩"),P("relieved","다행이에요","😮‍💨")]}],
 dialogs:[[['you',"My mom has been in the hospital this week.","이번 주에 엄마가 입원하셨어."],['me',"Oh no, I'm so sorry to hear that.","어머, 정말 안타깝다."],['you',"Thanks. It's been a long week.","고마워. 긴 한 주였어."],['me',"That must have been really hard.","정말 힘들었겠다."],['you',"Yeah, but she's getting better.","응, 그래도 점점 나아지고 계셔."],['me',"I'm here if you need anything. Hang in there.","필요한 거 있으면 말해. 조금만 힘내."]],
  [['you',"Guess what? My son got into his dream school!","있잖아! 우리 아들이 꿈꾸던 학교에 붙었어!"],['me',"No way! I'm so happy for you!","말도 안 돼! 정말 잘됐다!"],['you',"Thanks! He worked so hard.","고마워! 정말 열심히 했거든."],['me',"You must be so proud.","정말 뿌듯하겠다."],['you',"I really am.","진짜 그래."],['me',"We should celebrate!","축하해야지!"]]],
 missions:[`가족이나 친구에게 공감 표현 하나를 영어로 건네 보기`,`오늘 내 기분을 영어 세 문장으로 설명해 보기`]},

{id:'idioms',icon:'🌟',name:'원어민 관용구',desc:'자주 쓰는 원어민 표현',bg:'#e0e7ff',
 phrases:[P("It's a piece of cake.","식은 죽 먹기예요.","🍰"),P("Let's call it a day.","오늘은 여기까지 해요.","🌇"),P("I'm all ears.","잘 듣고 있어요, 말해 보세요.","👂"),P("It slipped my mind.","깜빡했어요.","💭"),P("Better late than never.","늦더라도 안 하는 것보단 나아요.","⏰"),P("I'm running late.","좀 늦을 것 같아요.","🏃"),P("Break a leg!","행운을 빌어요!","🍀"),P("It's on me.","제가 살게요.","💳")],
 patterns:[{en:"I'm running late for ___.",ko:"___에 늦을 것 같아요.",slots:[P("work","회사","💼"),P("my appointment","약속","📅"),P("pickup","아이 픽업","🚸"),P("class","수업","📚")]},
  {en:"___ is on me.",ko:"___ 제가 살게요.",slots:[P("Lunch","점심은","🥪"),P("Coffee","커피는","☕"),P("Dinner","저녁은","🍝"),P("This round","이번 잔은","🍻")]}],
 dialogs:[[['you',"Sorry, I totally forgot to send you the file.","미안, 파일 보내는 걸 완전히 깜빡했어."],['me',"No worries. Better late than never!","괜찮아. 늦더라도 안 하는 것보단 낫지!"],['you',"Thanks. It just slipped my mind.","고마워. 그냥 깜빡했어."],['me',"It happens. So, what did you want to tell me? I'm all ears.","그럴 수 있지. 그래서, 하고 싶은 말이 뭐야? 잘 듣고 있어."],['you',"I have a big presentation tomorrow.","내일 중요한 발표가 있어."],['me',"You'll do great. Break a leg!","잘할 거야. 행운을 빌어!"]],
  [['you',"Wow, it's already six. Let's call it a day.","와, 벌써 6시네. 오늘은 여기까지 하자."],['me',"Good idea. Want to grab dinner?","좋아. 저녁 먹으러 갈래?"],['you',"Sure. But first, I'm running late for pickup.","좋아. 근데 그 전에 아이 픽업에 늦을 것 같아."],['me',"No problem. Meet you there at seven?","괜찮아. 7시에 거기서 볼까?"],['you',"Perfect. Dinner is on me tonight.","완벽해. 오늘 저녁은 내가 살게."],['me',"Aw, you don't have to do that!","에이, 안 그래도 되는데!"]]],
 missions:[`오늘 배운 관용구 하나를 실제 상황에 맞춰 혼잣말해 보기`,`관용구 하나를 아이에게 뜻과 함께 알려 주기`]}
];
const LEVELS={
 beginner:{name:'초급',icon:'🌱',who:'아이 첫걸음',desc:'짧은 생활 표현을 듣고 따라 말해요.',adult:false,rate:.8,worlds:W_BEGINNER},
 intermediate:{name:'중급',icon:'🌿',who:'아이 다음 단계',desc:'조금 긴 문장으로 이유와 계획을 말해요.',adult:false,rate:.8,worlds:W_INTERMEDIATE},
 advanced:{name:'상급',icon:'🌳',who:'생활영어 가능한 성인',desc:'어른 생활 주제 · 한국어를 보고 영어로 먼저 말해요.',adult:true,rate:.95,worlds:W_ADVANCED},
 master:{name:'마스터',icon:'👑',who:'해외 생활 경험자',desc:'원어민 표현과 뉘앙스 · 원어민 속도 · 역할극 내 대사 숨김.',adult:true,rate:1.05,worlds:W_MASTER}
};
